name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: ""
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Black Linting
          title: Black Linting
          body: Automated Balc Linting by [create-pull-request](https://github.com/peter-evans/create-pull-request) trough GitHub action
          branch: python-black-linting/patch
          delete-branch: true
